# Generated by Django 5.0.2 on 2026-01-01 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('FLAT', 'Flat/Apartment'), ('VILLA', 'Villa/House'), ('LAND', 'Plot/Land'), ('STUDIO', 'Studio'), ('PENTHOUSE', 'Penthouse')], max_length=50)),
                ('bhk_config', models.IntegerField(choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4+ BHK')], default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('super_builtup_area', models.DecimalField(decimal_places=2, help_text='Total saleable area', max_digits=12)),
                ('carpet_area', models.DecimalField(decimal_places=2, help_text='RERA usable area', max_digits=12)),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('furnishing_status', models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('FULLY_FURNISHED', 'Fully Furnished')], default='UNFURNISHED', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('address_line', models.TextField()),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('landmarks', models.TextField(blank=True, help_text='Nearby Schools, Metro, etc.')),
                ('specific_floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('NORTH_EAST', 'North-East'), ('SOUTH_EAST', 'South-East'), ('NORTH_WEST', 'North-West'), ('SOUTH_WEST', 'South-West')], max_length=20, null=True)),
                ('availability_status', models.CharField(choices=[('READY', 'Ready to Move'), ('UNDER_CONSTRUCTION', 'Under Construction')], default='READY', max_length=20)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('age_of_construction', models.IntegerField(default=0, help_text='In years')),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_club_house', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_park', models.BooleanField(default=False)),
                ('has_reserved_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('is_vastu_compliant', models.BooleanField(default=False)),
                ('has_intercom', models.BooleanField(default=False)),
                ('has_piped_gas', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Hosted link', null=True)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/')),
                ('doc_7_12', models.FileField(blank=True, null=True, upload_to='properties/docs/7_12/')),
                ('doc_mojani', models.FileField(blank=True, null=True, upload_to='properties/docs/mojani/')),
                ('listed_by', models.CharField(choices=[('OWNER', 'Owner'), ('AGENT', 'Agent'), ('BUILDER', 'Builder')], default='OWNER', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_thumbnail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
