# Generated by Django 5.0.2 on 2026-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_description_alter_property_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('BUNGALOW', 'Bungalow'), ('TWIN_BUNGALOW', 'Twin Bungalow'), ('ROWHOUSE', 'Rowhouse'), ('VILLA', 'Villa'), ('RES_PLOT', 'Residential Plot'), ('COM_PLOT', 'Commercial Plot'), ('AGRI_LAND', 'Agricultural Land'), ('IND_LAND', 'Industrial Land'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('SHOWROOM', 'Showroom')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk_config',
            field=models.IntegerField(choices=[(1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4+ BHK'), (5, '5+ BHK')], default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='RERA usable area', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('VILLA_BUNGALOW', 'Villa / Bungalow / Rowhouse'), ('FLAT', 'Flat / Apartment'), ('PLOT', 'Plot (Residential / Commercial)'), ('LAND', 'Land (Agriculture / Industrial)'), ('COMMERCIAL_UNIT', 'Shop / Office / Showroom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='super_builtup_area',
            field=models.DecimalField(decimal_places=2, help_text='Total saleable area', max_digits=12),
        ),
    ]
