# Generated by Django 5.0.2 on 2026-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_sub_type_alter_property_bhk_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='doc_7_12',
        ),
        migrations.RemoveField(
            model_name='property',
            name='doc_mojani',
        ),
        migrations.AddField(
            model_name='property',
            name='building_commencement_certificate',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_completion_certificate',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='doc_7_12_or_pr_card',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='gst_registration',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='layout_order',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='layout_sanction',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='mojani_nakasha',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='na_order_or_gunthewari',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_project_certificate',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_deed_registration_copy',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_search_report',
            field=models.FileField(blank=True, null=True, upload_to='properties/docs/'),
        ),
    ]
