# Generated by Django 5.0.2 on 2026-01-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_property_doc_7_12_remove_property_doc_mojani_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_commencement_certificate',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_completion_certificate',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='doc_7_12_or_pr_card',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_order',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_sanction',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mojani_nakasha',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='na_order_or_gunthewari',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_search_report',
            field=models.FileField(null=True, upload_to='properties/docs/'),
        ),
    ]
