# Generated by Django 5.0.2 on 2026-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_propertyfloorplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='carpet_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RERA usable area', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='super_builtup_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total saleable area', max_digits=12, null=True),
        ),
    ]
