# Generated by Django 5.0.2 on 2026-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_carpet_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_children_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_drainage_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_internal_roads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_jogging_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_one_gate_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_street_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_temple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk_config',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Number of bedrooms. Use 0.5 for 1RK, 1-10 for standard BHK, 0 for N/A', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('BUNGALOW', 'Bungalow'), ('TWIN_BUNGALOW', 'Twin Bungalow'), ('ROWHOUSE', 'Rowhouse'), ('VILLA', 'Villa'), ('RES_PLOT', 'Residential Plot'), ('RES_PLOT_GUNTHEWARI', 'Residential Plot (Gunthewari)'), ('COM_PLOT', 'Commercial Plot'), ('AGRI_LAND', 'Agricultural Land'), ('IND_LAND', 'Industrial Land'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('SHOWROOM', 'Showroom')], max_length=50, null=True),
        ),
    ]
