# Generated by Django 5.0.2 on 2026-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_has_children_park_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balconies',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('FULLY_FURNISHED', 'Fully Furnished')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='specific_floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
