# Generated by Django 5.0.2 on 2026-01-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_property_balconies_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes (not visible to users)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured listings appear prominently on homepage'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin-verified property'),
        ),
        migrations.AddField(
            model_name='property',
            name='priority_listing',
            field=models.BooleanField(default=False, help_text='Higher priority in search results'),
        ),
    ]
