# Generated by Django 5.0.2 on 2026-01-01 01:47

import apps.mandates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('WITH_BROKER', 'With Broker'), ('WITH_PLATFORM', 'With Platform')], max_length=20)),
                ('initiated_by', models.CharField(choices=[('SELLER', 'Seller'), ('BROKER', 'Broker')], max_length=10)),
                ('is_exclusive', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Signature'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated Early')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_expires_at', models.DateTimeField(default=apps.mandates.models.get_acceptance_expiry)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('seller_signature', models.ImageField(blank=True, null=True, upload_to='signatures/sellers/')),
                ('broker_signature', models.ImageField(blank=True, null=True, upload_to='signatures/brokers/')),
            ],
        ),
    ]
