# Generated by Django 5.0.2 on 2026-01-01 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandates', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_mandates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandate',
            name='property_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='properties.property'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_mandates', to=settings.AUTH_USER_MODEL),
        ),
    ]
